baseURL = "https://ceeu21.github.io/"
languageCode = "es"
defaultContentLanguage = "es"
title = "Consejo Electoral Estudiantil Universitario"
theme = "ananke"
[params]
  site_logo = "/img/logo.svg"
  background_color_class = "bg-dark-blue"
  custom_css = ["css/custom.css"]
  featured_image = "/img/blue.png"
  facebook = "https://www.facebook.com/CEEU2021"
  twitter = "https://twitter.com/CEEU_21"
  instagram = "https://www.instagram.com/CEEU_21"